@extends('layouts.frontend')

@section('content')
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente alias error doloremque modi distinctio itaque accusantium dolorum delectus corporis vitae voluptas eaque porro sit quia inventore fugit quaerat, vero, ipsa adipisci laborum eligendi dolor nostrum atque. Asperiores deleniti, adipisci pariatur ipsa illum animi reiciendis accusantium ut corporis iure quo ea exercitationem delectus cupiditate eveniet ipsum libero harum. Architecto sit accusamus fuga necessitatibus, dolor porro unde dignissimos, nemo rem quis esse. Exercitationem suscipit asperiores, possimus, libero dolores voluptatum tempore inventore vero reiciendis quia tenetur. Dolorum numquam ut deserunt iusto ducimus dicta, perspiciatis ex facere quas ullam atque voluptatum esse aspernatur dignissimos? Fugit iusto debitis cum officia non, amet inventore nesciunt consectetur optio soluta dolorum perspiciatis quidem, voluptas ab vero nisi, ad saepe officiis quia repellat. Minus, est. Laboriosam excepturi autem maiores dignissimos, sunt sapiente, voluptate asperiores qui eveniet neque laborum tempora repellat delectus cum, aperiam optio expedita consequatur vel reiciendis illo. Fugiat natus, rem sunt commodi ea beatae alias facere quibusdam quia impedit! Tenetur obcaecati blanditiis quia eos exercitationem laboriosam nisi id, ex hic. Sed dignissimos, voluptatum debitis eligendi amet ut, placeat doloribus officiis consectetur perferendis magnam nulla tenetur perspiciatis earum possimus molestiae sint molestias, doloremque libero aspernatur suscipit dolorum rerum? Laborum vel maxime excepturi quas, dolor, placeat deserunt magnam minima fuga aliquid ab culpa doloremque et molestiae iure tempore. Expedita incidunt aspernatur ipsa quas earum nemo sapiente aperiam recusandae? Error enim, beatae atque accusamus, aspernatur nulla minima quaerat sunt amet facere porro ab, ipsa distinctio eos! Facilis ducimus itaque ipsum labore, iure provident fugiat dolorum, temporibus accusantium sed eveniet accusamus neque eligendi? Quaerat minus iste aperiam modi aspernatur debitis possimus dolore non, amet illum, earum recusandae suscipit repellendus quidem distinctio sequi delectus sapiente magni provident. Harum cumque voluptate blanditiis voluptas id quidem officia nam rem dicta, debitis odit saepe quae aspernatur adipisci fugit, praesentium sed, ullam iusto laboriosam pariatur eligendi. Perferendis, ex. Dignissimos architecto suscipit minima enim perferendis animi .</p>

@include('components.feature')

@endsection


